In [1]:
import tensorflow as tf
import numpy as np

In [2]:
train_label= np.loadtxt('train_label.txt',delimiter=',', dtype=np.float32)
train_label=train_label.reshape(-1,1)

test_label= np.loadtxt('test_label.txt',delimiter=',', dtype=np.float32)
test_label=test_label.reshape(-1,1)

train_img= np.loadtxt('train_img.txt',delimiter=',', dtype=np.float32)

test_img= np.loadtxt('test_img.txt',delimiter=',', dtype=np.float32)

train_img=tf.transpose(train_img)
train_img=tf.reshape(train_img,[-1,3*28*28])
test_img=tf.transpose(test_img)
test_img=tf.reshape(test_img,[-1,3*28*28])

In [7]:
tf.convert_to_tensor(img.eval())

In [7]:
train_img=train_img.T
train_img.shape
train_img=train_img.reshape(2000,3,28,28)
train_img[0,:,:,:]
train_img=np.swapaxes(train_img,2,3)

In [7]:
train_img=np.swapaxes(train_img,2,3)
train_img[0,:,:,:]
# 여기까지가 train_img.shape = 2000,3,28,28

ValueError: bad axis1 argument to swapaxes

In [8]:
train_img=train_img.reshape(2000,3*28*28)
train_img[0,:]
# 여기까지가 train_img.shape = 2000,3*28*28

array([  35.,  171.,  175., ...,   71.,   71.,   69.], dtype=float32)

In [9]:
train_img=train_img.reshape(2000,3,28,28)
train_img=np.swapaxes(train_img,1,2)
train_img=np.swapaxes(train_img,2,3)
train_img[0,:,:,:]
#여기까지가 train_img.shape = 2000,28,28,3

array([[[  35.,  169.,   35.],
        [ 171.,  171.,   37.],
        [ 175.,  175.,   41.],
        ..., 
        [ 205.,  205.,   69.],
        [  61.,  195.,   61.],
        [  59.,  193.,   59.]],

       [[  37.,  173.,   37.],
        [  41.,  175.,   41.],
        [ 181.,  181.,   45.],
        ..., 
        [ 203.,  203.,   67.],
        [  57.,  193.,   57.],
        [  57.,   57.,  191.]],

       [[  41.,  177.,   41.],
        [  45.,  181.,   45.],
        [  49.,  183.,   49.],
        ..., 
        [ 197.,  197.,   63.],
        [  53.,  189.,   53.],
        [  53.,  187.,   53.]],

       ..., 
       [[ 211.,  211.,   75.],
        [ 213.,  213.,   79.],
        [ 215.,  215.,   79.],
        ..., 
        [ 205.,  205.,   71.],
        [ 207.,  207.,   71.],
        [ 207.,  207.,   71.]],

       [[ 213.,  213.,   77.],
        [ 215.,  215.,   79.],
        [ 215.,  215.,   79.],
        ..., 
        [ 205.,  205.,   71.],
        [ 205.,  205.,   71.],
        [ 

In [10]:
tf.reset_default_graph()
learning_rate = 0.001
training_epochs = 2
batch_size = 50

X=tf.placeholder(tf.float32, [None, 3*28*28])
X_img=tf.reshape(X, [-1,3, 28, 28])
X_img=tf.transpose(X_img, [0, 2, 3, 1])

Y=tf.placeholder(tf.int32, [None, 1])
Y_one_hot=tf.one_hot(Y, 2)
Y_one_hot=tf.reshape(Y_one_hot, [-1,2])

W1 = tf.get_variable("W1", shape=[3,3,3,32], initializer=tf.contrib.layers.xavier_initializer())
L1=tf.nn.conv2d(X_img, W1, strides=[1,1,1,1], padding='SAME')
L1=tf.nn.relu(L1)
L1=tf.nn.max_pool(L1, ksize=[1,2,2,1], strides=[1,2,2,1], padding='SAME')

W2 = tf.get_variable("W2", shape=[3,3,32,64], initializer=tf.contrib.layers.xavier_initializer())
L2=tf.nn.conv2d(L1, W2, strides=[1,1,1,1], padding='SAME')
L2=tf.nn.relu(L2)
L2=tf.nn.max_pool(L2, ksize=[1,2,2,1], strides=[1,2,2,1], padding='SAME')
L2=tf.reshape(L2, [-1,7*7*64*3])

W3=tf.get_variable('W3', shape=[3*7*7*64, 2], initializer=tf.contrib.layers.xavier_initializer())
b=tf.Variable(tf.random_normal([2]))
hypothesis=tf.matmul(L2, W3) + b

cost=tf.reduce_mean(tf.nn.softmax_cross_entropy_with_logits(logits=hypothesis, labels=Y_one_hot))
optimizer=tf.train.AdamOptimizer(learning_rate=learning_rate).minimize(cost)

sess=tf.Session()
sess.run(tf.global_variables_initializer())

print('Learning started.')

for epoch in range(training_epochs):
    avg_cost = 0
    total_batch = int(2000 / 50)

    for i in range(total_batch):
        batch_xs, batch_ys = tf.train.batch([train_img, train_label], batch_size=50, enqueue_many=True)
        #c, _ = sess.run([cost, optimizer], feed_dict={X: batch_xs, Y: batch_ys})
        c = cost.eval(session=sess, feed_dict={X: batch_xs, Y: batch_ys})
        _ = optimizer.eval(session=sess, feed_dict={X: batch_xs, Y: batch_ys})
        avg_cost += c / total_batch

    print('Epoch:', '%04d' % (epoch + 1), 'cost =', '{:.9f}'.format(avg_cost))

print('Learning Finished!')

# Test model and check accuracy
correct_prediction = tf.equal(tf.argmax(hypothesis, 1), tf.argmax(Y_one_hot, 1))
accuracy = tf.reduce_mean(tf.cast(correct_prediction, tf.float32))
print('Accuracy:', sess.run(accuracy, feed_dict={
      X: test_img, Y: test_label}))

Learning started.


TypeError: The value of a feed cannot be a tf.Tensor object. Acceptable feed values include Python scalars, strings, lists, numpy ndarrays, or TensorHandles.

In [6]:
sess = tf.Session()
with sess.as_default():
    print(tf.constant([1,2,3]).eval())
    
tf.constant([1,2,3]).shape

[1 2 3]


TensorShape([Dimension(3)])

In [6]:
sess=tf.Session()
sess.run(tf.global_variables_initializer())
batch_xs, batch_ys = tf.train.batch([train_img, train_label], batch_size=50, enqueue_many=True)
with sess.as_default():
    batch_xs, batch_ys = batch_xs.eval(), batch_ys.eval()

ValueError: Cannot use the default session to evaluate tensor: the tensor's graph is different from the session's graph. Pass an explicit session to `eval(session=sess)`.